service: miz
frameworkVersion: '2'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  main:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: POST

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true

plugins:
  - serverless-esbuild
  - serverless-offline
